# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x18\n\x06UserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"C\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.ShowTime\x12\n\n\x02id\x18\x03 \x01(\t\"4\n\x08ShowTime\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06movies\x18\x03 \x03(\t\"\x16\n\x04User\x12\x0e\n\x06userid\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x8f\x01\n\x07\x42ooking\x12.\n\x11GetBookingsByUser\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x30\x01\x12\'\n\x0bGetBookings\x12\x06.Empty\x1a\x0c.BookingData\"\x00\x30\x01\x12+\n\x10\x41\x64\x64\x42ookingByUser\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=41
  _globals['_BOOKINGDATA']._serialized_start=43
  _globals['_BOOKINGDATA']._serialized_end=110
  _globals['_SHOWTIME']._serialized_start=112
  _globals['_SHOWTIME']._serialized_end=164
  _globals['_USER']._serialized_start=166
  _globals['_USER']._serialized_end=188
  _globals['_EMPTY']._serialized_start=190
  _globals['_EMPTY']._serialized_end=197
  _globals['_BOOKING']._serialized_start=200
  _globals['_BOOKING']._serialized_end=343
# @@protoc_insertion_point(module_scope)
